engines:
        gofmt:
                enabled: true
        golint:
                enabled: true
        govet:
                enabled: true
        csslint:
                enabled: true
        markdownlint:
                enabled: true
ratings:
        paths:
                - "**.go"
                - "**.css"
                - "**.md"
